-- Migration: seed initial projects
-- Created by Wrangler

INSERT INTO projects (title, slug, description, tech_stack, live_url, github_url, image_url) VALUES
('Cloudflare Portfolio', 'cloudflare-portfolio', 'A modern portfolio website built with React, Vite, Hono, and Cloudflare Workers. Features D1 database integration, edge-native architecture, and dark mode support.', '["React","TypeScript","Vite","Hono","Cloudflare Workers","D1","Tailwind CSS"]', 'https://steves-portfolio.pages.dev', 'https://github.com/TechDeca/steves-portfolio-cf', '/images/projects/cloudflare-portfolio.svg'),
('Task Management API', 'task-management-api', 'A RESTful API for task management with JWT authentication, built on Cloudflare Workers using Hono. Supports full CRUD operations with D1 persistence and rate limiting.', '["Hono","TypeScript","Cloudflare Workers","D1","JWT"]', 'https://task-api.example.com', 'https://github.com/TechDeca/task-api', '/images/projects/task-api.svg'),
('E-Commerce Dashboard', 'ecommerce-dashboard', 'A responsive admin dashboard for e-commerce platforms featuring real-time analytics, inventory management, order tracking, and interactive data visualizations.', '["React","TypeScript","Tailwind CSS","Chart.js"]', 'https://dashboard.example.com', 'https://github.com/TechDeca/ecommerce-dashboard', '/images/projects/ecommerce-dashboard.svg'),
('Real-time Chat App', 'realtime-chat', 'A WebSocket-powered chat application with real-time messaging, private and group rooms, typing indicators, and online presence detection.', '["React","TypeScript","Socket.io","Node.js","Express"]', 'https://chat.example.com', 'https://github.com/TechDeca/realtime-chat', '/images/projects/realtime-chat.svg'),
('Weather Dashboard', 'weather-dashboard', 'An interactive weather application with geolocation-based forecasts, 7-day predictions, hourly breakdowns, and severe weather alert notifications.', '["React","TypeScript","OpenWeather API","Chart.js"]', 'https://weather.example.com', 'https://github.com/TechDeca/weather-dashboard', '/images/projects/weather-dashboard.svg');
